namespace Pico.DI.Abs;

/// <summary>
/// Provides a mechanism for source-generated code to automatically configure containers.
/// The source generator registers a configuration action via <see cref="RegisterConfigurator"/>,
/// and <see cref="SvcContainer"/> automatically invokes it during construction.
/// </summary>
public static class SvcContainerAutoConfiguration
{
    private static readonly List<Action<ISvcContainer>> _configurators = new();

    /// <summary>
    /// Registers a configurator action that will be automatically invoked when a new container is created.
    /// This method is typically called from a Module Initializer generated by Pico.DI.Gen.
    /// Multiple configurators can be registered and will be invoked in registration order.
    /// </summary>
    /// <param name="configurator">The configuration action that registers services with the container.</param>
    public static void RegisterConfigurator(Action<ISvcContainer> configurator)
    {
        lock (_configurators)
        {
            _configurators.Add(configurator);
        }
    }

    /// <summary>
    /// Applies all registered configurations to the given container.
    /// This method is called internally by <see cref="SvcContainer"/> during construction.
    /// </summary>
    /// <param name="container">The container to configure.</param>
    /// <returns>True if any configurators were registered and applied; otherwise, false.</returns>
    public static bool TryApplyConfiguration(ISvcContainer container)
    {
        Action<ISvcContainer>[] configurators;
        lock (_configurators)
        {
            if (_configurators.Count == 0)
                return false;
            configurators = _configurators.ToArray();
        }

        foreach (var configurator in configurators)
        {
            configurator(container);
        }
        return true;
    }

    /// <summary>
    /// Gets a value indicating whether any configurators have been registered.
    /// </summary>
    public static bool HasConfigurator
    {
        get
        {
            lock (_configurators)
            {
                return _configurators.Count > 0;
            }
        }
    }
}
