namespace Pico.DI.Abs;

/// <summary>
/// Provides a mechanism for source-generated code to automatically configure containers.
/// The source generator registers a configuration action via <see cref="RegisterConfigurator"/>,
/// and <see cref="SvcContainer"/> automatically invokes it during construction.
/// </summary>
public static class SvcContainerAutoConfiguration
{
    private static Action<ISvcContainer>? _configurator;

    /// <summary>
    /// Registers a configurator action that will be automatically invoked when a new container is created.
    /// This method is typically called from a Module Initializer generated by Pico.DI.Gen.
    /// </summary>
    /// <param name="configurator">The configuration action that registers services with the container.</param>
    public static void RegisterConfigurator(Action<ISvcContainer> configurator)
    {
        _configurator = configurator;
    }

    /// <summary>
    /// Applies the registered configuration to the given container.
    /// This method is called internally by <see cref="SvcContainer"/> during construction.
    /// </summary>
    /// <param name="container">The container to configure.</param>
    /// <returns>True if a configurator was registered and applied; otherwise, false.</returns>
    public static bool TryApplyConfiguration(ISvcContainer container)
    {
        if (_configurator is null)
            return false;

        _configurator(container);
        return true;
    }

    /// <summary>
    /// Gets a value indicating whether a configurator has been registered.
    /// </summary>
    public static bool HasConfigurator => _configurator is not null;
}
